language: node_js
node_js:
- '0.10'
- '0.12'
notifications:
  hipchat:
    rooms:
      secure: G86agoGJWFpnW+DIwoY0iZjTi4858qgZUnVSFKkz39zfeIFm/lnmcBG3MqLMzvkjFrj+qoofqAUUbycvA8ZE7FbX6+rOfChPpco14LM/cPWrltNuLEYGHA5ikLTrGXOQpy6HFx0MFxhDQc5GFZWoNOVZb8bRogyv1PZwS2AG7tQ=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    format: html
deploy:
  provider: npm
  email: corey@coreybutler.com
  api_key:
    secure: U5B2k7e9rHrR8eX34Xs36MHChqYDHCA/gdq38kLaXlkuJqsMqWPooeWr4wtxRGxPMkDqbYWKgGfPP7puASTKpJ/KHM0HwNv0eS3Rq3StRsjkRC26A2u4s6N9F1lQJim1J/Ju4UVuU2Yup8Z5o8lCGeZvpsinTP957+Hmc55LsSI=
  on:
    tags: true
    repo: coreybutler/musthave
